"""empty message

Revision ID: 111e20ed3a91
Revises: 4abff98672a0
Create Date: 2023-07-14 15:20:44.026887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '111e20ed3a91'
down_revision = '4abff98672a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.drop_column('join_time')
        batch_op.drop_column('paseord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paseord', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('join_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
