"""empty message

Revision ID: 4abff98672a0
Revises: 7421f427f314
Create Date: 2023-07-14 14:46:45.604864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4abff98672a0'
down_revision = '7421f427f314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
