"""empty message

Revision ID: 7421f427f314
Revises: c6758c1c8966
Create Date: 2023-07-14 14:09:23.715278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7421f427f314'
down_revision = 'c6758c1c8966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
